# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'edl_billing'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'edl_billing'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ['models']
analysis-paths: ['analyses']
test-paths: ['tests']
seed-paths: ['seeds']
macro-paths: ['macros']
snapshot-paths: ['snapshots']
docs-paths: ['docs']
asset-paths: ['assets']

clean-targets: # directories to be removed by `dbt clean`
  - 'target'
  - 'dbt_packages'

models:
  edl_billing:
    2_staging:
      +schema: staging
      +materialized: table # materialize as tables
      +transient: true # do not create table as transient (which is the default behavior of snowflake)
    3_marts:
      +materialized: table # materialize as tables
      +transient: false # do not create table as transient (which is the default behavior of snowflake)
      +persist_docs: # persist resource descriptions as column and relation comments in the database
        relation: true
        columns: true

vars:
  edl_billing:
    # generate dates between the following dates and populate dim_date
    start_date: '2021-01-01'
    end_date: '2030-12-31'

on-run-start: '{{ generate_sequences() }}' # generates sequences for dimensions if not exists
